### ISSUE TITLE
An oversight in airdrop.inc

### ISSUE THREAD

**Issue by Daniel-Cortez** [opencnr/gamemode#12]
The following code from function `UpdateAirdropTimer` in `airdrop.inc` looks suspicious: https://github.com/opencnr/gamemode/blob/bdfe8b08ab66a2f20004f8b9302e1d9c041d51b6/gamemodes/opencnr/airdrop/airdrop.inc#L120
Global variables `movetoX` and `movetoY` are used on this line, but they weren't assigned any value throughout the whole file (so they contain `0` by default).

You'll probably want to either assign some values to these variables (if that's what you initially intended), or just remove them completely.

**Comment by thecodeah** [comment]
Hmmm. Yeah, that is weird. I'm not sure why that's even there.
This module in particular was one that I had repurposed from an old game-mode and slightly rewrote.

I'll remove the variables, thanks for the issue!

**Comment by thecodeah** [comment]
Resolved with 312e043
