### ISSUE TITLE
Use the deathlist for connect/disconnect

### ISSUE THREAD

**Issue by ADRFranklin** [opencnr/gamemode#13]
Since you are not planning on using the death list system for kills, you could use it for showing players who disconnect and connect to the server.

So as to not pollute the chat, and not need to mess with textdraws.

**Comment by thecodeah** [comment]
The font doesn't seem to be loaded in when playing SA-MP on Linux using Wine. Aside from that I think the placement is a bit odd.

Perhaps we'd be better off with an alternative to the Death/Kill list?

![image](https://user-images.githubusercontent.com/21268739/61862690-f51c0780-aed6-11e9-941b-47779381fab1.png)

**Comment by devlexanderxyz** [comment]
Just a suggestion-- you could use textdraws?

**Comment by thecodeah** [comment]
Yeah, that and the chat are the only alternatives.

But there are multiple reasons why it'd just be better to not have this feature at all :
 - Textdraws are a pain to work with
 - Textdraw fonts are all either bold or cursive-like, it'd look odd and it would be too intrusive
 - This information isn't really important anyways. Just showing that a friend has joined in the chat is good enough.

**Comment by AmirSavand** [comment]
@thecodeah I agree. It's a waste of time to make them with text draws. Chat is enough, you don't want the death feed to be ruined with join/leave.
